version: '3'
services:
  redis-server:
    image: 'redis'

  db-server:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'test_proj_db'
      MYSQL_USER: 'trp-user'
      MYSQL_PASSWORD: 'casigh4fuweb'
      MYSQL_ROOT_PASSWORD: 'asfdsf4sw4ew'
  app-server:
    build: .
    command: gunicorn testproj.wsgi:application --bind 0.0.0.0:8000
    environment:
      PYTHONUNBUFFERED: '1'
      PYTHONDONTWRITEBYTECODE: '1'
      MYSQL_DATABASE: 'test_proj_db'
      MYSQL_USER: 'trp-user'
      MYSQL_PASSWORD: 'casigh4fuweb'
    ports:
      - "8000:8000"